# Generated by Django 6.1 on 2026-09-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='order',
            name='product',
        ),

        migrations.AddField(
            model_name='order',
            name='bot_description',
            field=models.TextField(
                blank=True
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(
                default='',
                max_length=150
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(
                choices=[
                    ('website', 'Web sayt'),
                    ('bot', 'Telegram bot'),
                    ('program', 'Dastur'),
                    ('design', 'Dizayn'),
                ],
                default='website',
                max_length=30
            ),
            preserve_default=False,
        ),
    ]